# Generated by Django 3.2.19 on 2023-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='records',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
